# https://zh.wikipedia.org/wiki/YAML
# https://github.com/travis-ci/travis.rb#table-of-contents
# https://docs.travis-ci.com/
language: python
python: 
  - "3.8"

install:
  - pip install -r requirements.txt

script: 
  - python researchacademic/test_fetcher.py

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password: {{PASSWD}}
  on:
    tags: true
