language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python researchacademic/test_fetcher.py
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password: 
    secure: Wg7ulLnXNuAkefv4dzVWDpZbD278dA4C5SOuNNb2T07KkdRg0UvhOO0CKjaQPDNO6sEVm7RmIPgA/uk8Z8ezOb0BoIYHapsQtjKj/nFUj0cOHLtQGUu3DyaqsydbSwqjLol0hHTawZEzwYuNKjMYHK7A9l2OyM3WErIDkBfmS31EPvrSiI+YWowiRszRT/unJOPNh3sBuPW1otm5084xy8PQuzjKF4G9XNjY7NZo6VXeBCWGUSExcPou/vMCOqJUvccoEEuY0UBp0xc8eNHjSdcxCQs5y6Ege0s3giD+NQitKMjBNzoekjX3NDnsPkc6+ZT07WHn3tJX6w5+yXX0YIEYLqSggGIT8rLwptVbLPNsC61kF0QJ9uI84cR/gDa6DjakFsxim+FzfmxfuJYwW5L1u7tORuHFjAfzUezbd1d/t08vKOgIbwlr+mNBsBxsBIvSpQdLByq66u72Z5hFjSS60U8sdhPEdJbWdwZQgg8RCPyEWGUKr7l9xIrWUP3Leo2p4t/6CeFx6Wpb7gxO5Nf1F63DWY4T9GHqDbMsxvu0HcjuO2ggFJWplOT5P9eJbuvCeNlPqwIvlpUIig7TkV+Jg+rf0mnboAseNncl+RZ6VGeWCT0FECg5hxGxZaEFU9GsDVHNL1M1FhYpU44hV8KWyoMtdcccO4xRx67s7yE=
  on:
    tags: true
